stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cp botdbconnect /usr/lib/golang/src/
    - go build main.go
    - docker build -t bot .
    - docker build -t adminbot /home/asmolin/go/bot/adminbotdocker/
deploy-job:
  stage: deploy
  script: 
    - docker run --name bot -d bot
    - docker run --name adminbot -p 80:80 adminbot